name: ProSchematicBuilder
authors: [Weefle, Sentropic]
version: ${project.version}
main: fr.weefle.constructor.SchematicBuilder
depends: [ProMCCore, Citizens]
softdepends: [Denizen, dynmap]
api-version: 1.14
commands:
  schematicbuilder:
    description: Lists SchematicBuilder commands.
    usage: /schematicbuilder help
permissions:
  schematicbuilder.*:
    default: op
    children:
      schematicbuilder.reload: true
      schematicbuilder.load: true
      schematicbuilder.npc: true
      schematicbuilder.cancel: true
      schematicbuilder.excavated: true
      schematicbuilder.preview: true
      schematicbuilder.structure: true
      schematicbuilder.build: true
      schematicbuilder.mark: true
      schematicbuilder.origin: true
      schematicbuilder.check: true
      schematicbuilder.compare: true
      schematicbuilder.info: true
      schematicbuilder.survey: true
      schematicbuilder.timeout: true
      schematicbuilder.ignoreprotection: true
      schematicbuilder.list: true
      schematicbuilder.hold: true
      schematicbuilder.supply: true
      schematicbuilder.donate: true
      schematicbuilder.select: true
      schematicbuilder.npc.click: true